from afterpay.exceptions.unexpected_error import UnexpectedError

class ConnectionError(UnexpectedError):
    pass
