2021-12-16 23:58:49.831 | DEBUG    | aria2p.api:pause:538 - Failed to pause download 0a6635c602761000
2021-12-16 23:58:49.831 | TRACE    | aria2p.api:pause:539 - GID 0a6635c602761000 is not found
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>

  File "/home/pawamoy/.cache/pdm/packages/execnet-1.9.0-py2.py3-none-any/lib/execnet/gateway_base.py", line 1554, in serve
    WorkerGateway(io=io, id=id, _startcount=2).serve()
    │                │      └ 'gw2-worker'
    │                └ <execnet.gateway_base.Popen2IO object at 0x7f388db3a8c0>
    └ <class 'execnet.gateway_base.WorkerGateway'>

  File "/home/pawamoy/.cache/pdm/packages/execnet-1.9.0-py2.py3-none-any/lib/execnet/gateway_base.py", line 1060, in serve
    self._execpool.integrate_as_primary_thread()
    │    │         └ <function WorkerPool.integrate_as_primary_thread at 0x7f388dbb3a60>
    │    └ <execnet.gateway_base.WorkerPool object at 0x7f388da81180>
    └ <execnet.gateway_base.WorkerGateway object at 0x7f388da5b540>

  File "/home/pawamoy/.cache/pdm/packages/execnet-1.9.0-py2.py3-none-any/lib/execnet/gateway_base.py", line 267, in integrate_as_primary_thread
    self._perform_spawn(reply)
    │    │              └ <execnet.gateway_base.Reply object at 0x7f388da81940>
    │    └ <function WorkerPool._perform_spawn at 0x7f388dbb3c40>
    └ <execnet.gateway_base.WorkerPool object at 0x7f388da81180>

  File "/home/pawamoy/.cache/pdm/packages/execnet-1.9.0-py2.py3-none-any/lib/execnet/gateway_base.py", line 285, in _perform_spawn
    reply.run()
    │     └ <function Reply.run at 0x7f388dbb3920>
    └ <execnet.gateway_base.Reply object at 0x7f388da81940>

  File "/home/pawamoy/.cache/pdm/packages/execnet-1.9.0-py2.py3-none-any/lib/execnet/gateway_base.py", line 220, in run
    self._result = func(*args, **kwargs)
    │              │     │       └ {}
    │              │     └ ((<Channel id=1 open>, ('"""\n    This module is executed in remote subprocesses and helps to\n    control a remote testing s...
    │              └ <bound method WorkerGateway.executetask of <execnet.gateway_base.WorkerGateway object at 0x7f388da5b540>>
    └ <execnet.gateway_base.Reply object at 0x7f388da81940>

  File "/home/pawamoy/.cache/pdm/packages/execnet-1.9.0-py2.py3-none-any/lib/execnet/gateway_base.py", line 1084, in executetask
    do_exec(co, loc)  # noqa
    │       │   └ {'channel': <Channel id=1 open>, '__name__': '__channelexec__', '__builtins__': {'__name__': 'builtins', '__doc__': "Built-in...
    │       └ <code object <module> at 0x7f388da7dfb0, file "/home/pawamoy/.cache/pdm/packages/pytest_xdist-2.5.0-py3-none-any/lib/xdist/re...
    └ <built-in function exec>

  File "/home/pawamoy/.cache/pdm/packages/pytest_xdist-2.5.0-py3-none-any/lib/xdist/remote.py", line 291, in <module>
    config.hook.pytest_cmdline_main(config=config)
    │      │    │                          └ <_pytest.config.Config object at 0x7f388c519780>
    │      │    └ <_HookCaller 'pytest_cmdline_main'>
    │      └ <pluggy._hooks._HookRelay object at 0x7f388c50d0c0>
    └ <_pytest.config.Config object at 0x7f388c519780>

  File "/home/pawamoy/.cache/pdm/packages/pluggy-1.0.0-py2.py3-none-any/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'config': <_pytest.config.Config object at 0x7f388c519780>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f388c7ecae0>
           │    │         │    │     └ <_HookCaller 'pytest_cmdline_main'>
           │    │         │    └ 'pytest_cmdline_main'
           │    │         └ <_HookCaller 'pytest_cmdline_main'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f388c50cf80>>
           └ <_HookCaller 'pytest_cmdline_main'>

  File "/home/pawamoy/.cache/pdm/packages/pluggy-1.0.0-py2.py3-none-any/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'config': <_pytest.config.Config object at 0x7f388c519780>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/home/pawamoy/.cache/pdm/packages/pytest-6.2.5-py3-none-an...
           │    │               └ 'pytest_cmdline_main'
           │    └ <function _multicall at 0x7f388c7af2e0>
           └ <_pytest.config.PytestPluginManager object at 0x7f388c50cf80>

  File "/home/pawamoy/.cache/pdm/packages/pluggy-1.0.0-py2.py3-none-any/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<_pytest.config.Config object at 0x7f388c519780>]
          │         └ <function pytest_cmdline_main at 0x7f388c7613a0>
          └ <HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/home/pawamoy/.cache/pdm/packages/pytest-6.2.5-py3-none-any...

  File "/home/pawamoy/.cache/pdm/packages/pytest-6.2.5-py3-none-any/lib/_pytest/main.py", line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
           │            │       └ <function _main at 0x7f388c761440>
           │            └ <_pytest.config.Config object at 0x7f388c519780>
           └ <function wrap_session at 0x7f388c761300>

  File "/home/pawamoy/.cache/pdm/packages/pytest-6.2.5-py3-none-any/lib/_pytest/main.py", line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
    │       │            │    │       └ <Session tests exitstatus=ExitCode.OK testsfailed=0 testscollected=476>
    │       │            │    └ <_pytest.config.Config object at 0x7f388c519780>
    │       │            └ <function _main at 0x7f388c761440>
    │       └ ExitCode.OK
    └ <Session tests exitstatus=ExitCode.OK testsfailed=0 testscollected=476>

  File "/home/pawamoy/.cache/pdm/packages/pytest-6.2.5-py3-none-any/lib/_pytest/main.py", line 323, in _main
    config.hook.pytest_runtestloop(session=session)
    │      │    │                          └ <Session tests exitstatus=ExitCode.OK testsfailed=0 testscollected=476>
    │      │    └ <_HookCaller 'pytest_runtestloop'>
    │      └ <pluggy._hooks._HookRelay object at 0x7f388c50d0c0>
    └ <_pytest.config.Config object at 0x7f388c519780>

  File "/home/pawamoy/.cache/pdm/packages/pluggy-1.0.0-py2.py3-none-any/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'session': <Session tests exitstatus=ExitCode.OK testsfailed=0 testscollected=476>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f388c7ecae0>
           │    │         │    │     └ <_HookCaller 'pytest_runtestloop'>
           │    │         │    └ 'pytest_runtestloop'
           │    │         └ <_HookCaller 'pytest_runtestloop'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f388c50cf80>>
           └ <_HookCaller 'pytest_runtestloop'>

  File "/home/pawamoy/.cache/pdm/packages/pluggy-1.0.0-py2.py3-none-any/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'session': <Session tests exitstatus=ExitCode.OK testsfailed=0 testscollected=476>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/home/pawamoy/.cache/pdm/packages/pytest-6.2.5-py3-none-an...
           │    │               └ 'pytest_runtestloop'
           │    └ <function _multicall at 0x7f388c7af2e0>
           └ <_pytest.config.PytestPluginManager object at 0x7f388c50cf80>

  File "/home/pawamoy/.cache/pdm/packages/pluggy-1.0.0-py2.py3-none-any/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Session tests exitstatus=ExitCode.OK testsfailed=0 testscollected=476>]
          │         └ <bound method WorkerInteractor.pytest_runtestloop of <__channelexec__.WorkerInteractor object at 0x7f388c361040>>
          └ <HookImpl plugin_name='139880847249472', plugin=<__channelexec__.WorkerInteractor object at 0x7f388c361040>>

  File "/home/pawamoy/.cache/pdm/packages/pytest_xdist-2.5.0-py3-none-any/lib/xdist/remote.py", line 91, in pytest_runtestloop
    self.run_one_test(torun)
    │    │            └ [336, 337, 338]
    │    └ <function WorkerInteractor.run_one_test at 0x7f388c506520>
    └ <__channelexec__.WorkerInteractor object at 0x7f388c361040>

  File "/home/pawamoy/.cache/pdm/packages/pytest_xdist-2.5.0-py3-none-any/lib/xdist/remote.py", line 110, in run_one_test
    self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
    │    │      │    │                            │              └ <Function test_init_method>
    │    │      │    │                            └ <Function test_pause>
    │    │      │    └ <_HookCaller 'pytest_runtest_protocol'>
    │    │      └ <pluggy._hooks._HookRelay object at 0x7f388c50d0c0>
    │    └ <_pytest.config.Config object at 0x7f388c519780>
    └ <__channelexec__.WorkerInteractor object at 0x7f388c361040>

  File "/home/pawamoy/.cache/pdm/packages/pluggy-1.0.0-py2.py3-none-any/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'item': <Function test_pause>, 'nextitem': <Function test_init_method>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f388c7ecae0>
           │    │         │    │     └ <_HookCaller 'pytest_runtest_protocol'>
           │    │         │    └ 'pytest_runtest_protocol'
           │    │         └ <_HookCaller 'pytest_runtest_protocol'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f388c50cf80>>
           └ <_HookCaller 'pytest_runtest_protocol'>

  File "/home/pawamoy/.cache/pdm/packages/pluggy-1.0.0-py2.py3-none-any/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'item': <Function test_pause>, 'nextitem': <Function test_init_method>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/home/pawamoy/.cache/pdm/packages/pytest-6.2.5-py3-non...
           │    │               └ 'pytest_runtest_protocol'
           │    └ <function _multicall at 0x7f388c7af2e0>
           └ <_pytest.config.PytestPluginManager object at 0x7f388c50cf80>

  File "/home/pawamoy/.cache/pdm/packages/pluggy-1.0.0-py2.py3-none-any/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_pause>, <Function test_init_method>]
          │         └ <function pytest_runtest_protocol at 0x7f3887f61ee0>
          └ <HookImpl plugin_name='rerunfailures', plugin=<module 'pytest_rerunfailures' from '/home/pawamoy/.cache/pdm/packages/pytest_r...

  File "/home/pawamoy/.cache/pdm/packages/pytest_rerunfailures-9.1.1-py3-none-any/lib/pytest_rerunfailures.py", line 240, in pytest_runtest_protocol
    reports = runtestprotocol(item, nextitem=nextitem, log=False)
              │               │              └ <Function test_init_method>
              │               └ <Function test_pause>
              └ <function runtestprotocol at 0x7f388c7474c0>

  File "/home/pawamoy/.cache/pdm/packages/pytest-6.2.5-py3-none-any/lib/_pytest/runner.py", line 126, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
    │       │      │               │             └ False
    │       │      │               └ <Function test_pause>
    │       │      └ <function call_and_report at 0x7f388c747ba0>
    │       └ <method 'append' of 'list' objects>
    └ [<TestReport 'test_downloads.py::TestDownloadClass::test_pause' when='setup' outcome='passed'>]

  File "/home/pawamoy/.cache/pdm/packages/pytest-6.2.5-py3-none-any/lib/_pytest/runner.py", line 215, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
           │                 │     │       └ {}
           │                 │     └ 'call'
           │                 └ <Function test_pause>
           └ <function call_runtest_hook at 0x7f388c747ce0>

  File "/home/pawamoy/.cache/pdm/packages/pytest-6.2.5-py3-none-any/lib/_pytest/runner.py", line 254, in call_runtest_hook
    return CallInfo.from_call(
           │        └ <classmethod(<function CallInfo.from_call at 0x7f388c760360>)>
           └ <class '_pytest.runner.CallInfo'>

  File "/home/pawamoy/.cache/pdm/packages/pytest-6.2.5-py3-none-any/lib/_pytest/runner.py", line 311, in from_call
    result: Optional[TResult] = func()
            │        │          └ <function call_runtest_hook.<locals>.<lambda> at 0x7f3885d4fec0>
            │        └ +TResult
            └ typing.Optional

  File "/home/pawamoy/.cache/pdm/packages/pytest-6.2.5-py3-none-any/lib/_pytest/runner.py", line 255, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
            │          │       └ {}
            │          └ <Function test_pause>
            └ <_HookCaller 'pytest_runtest_call'>

  File "/home/pawamoy/.cache/pdm/packages/pluggy-1.0.0-py2.py3-none-any/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ False
           │    │         │    │     │    │                └ {'item': <Function test_pause>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f388c7ecae0>
           │    │         │    │     └ <_HookCaller 'pytest_runtest_call'>
           │    │         │    └ 'pytest_runtest_call'
           │    │         └ <_HookCaller 'pytest_runtest_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f388c50cf80>>
           └ <_HookCaller 'pytest_runtest_call'>

  File "/home/pawamoy/.cache/pdm/packages/pluggy-1.0.0-py2.py3-none-any/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ False
           │    │               │          │        └ {'item': <Function test_pause>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/home/pawamoy/.cache/pdm/packages/pytest-6.2.5-py3-non...
           │    │               └ 'pytest_runtest_call'
           │    └ <function _multicall at 0x7f388c7af2e0>
           └ <_pytest.config.PytestPluginManager object at 0x7f388c50cf80>

  File "/home/pawamoy/.cache/pdm/packages/pluggy-1.0.0-py2.py3-none-any/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_pause>]
          │         └ <function pytest_runtest_call at 0x7f388c7476a0>
          └ <HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/home/pawamoy/.cache/pdm/packages/pytest-6.2.5-py3-none...

  File "/home/pawamoy/.cache/pdm/packages/pytest-6.2.5-py3-none-any/lib/_pytest/runner.py", line 162, in pytest_runtest_call
    item.runtest()
    │    └ <function Function.runtest at 0x7f388c5c0040>
    └ <Function test_pause>

  File "/home/pawamoy/.cache/pdm/packages/pytest-6.2.5-py3-none-any/lib/_pytest/python.py", line 1641, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
    │    │                                   └ <Function test_pause>
    │    └ <property object at 0x7f388c6fc720>
    └ <Function test_pause>

  File "/home/pawamoy/.cache/pdm/packages/pluggy-1.0.0-py2.py3-none-any/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'pyfuncitem': <Function test_pause>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f388c7ecae0>
           │    │         │    │     └ <_HookCaller 'pytest_pyfunc_call'>
           │    │         │    └ 'pytest_pyfunc_call'
           │    │         └ <_HookCaller 'pytest_pyfunc_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f388c50cf80>>
           └ <_HookCaller 'pytest_pyfunc_call'>

  File "/home/pawamoy/.cache/pdm/packages/pluggy-1.0.0-py2.py3-none-any/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'pyfuncitem': <Function test_pause>}
           │    │               │          └ [<HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/home/pawamoy/.cache/pdm/packages/pytest-6.2.5-py3-non...
           │    │               └ 'pytest_pyfunc_call'
           │    └ <function _multicall at 0x7f388c7af2e0>
           └ <_pytest.config.PytestPluginManager object at 0x7f388c50cf80>

  File "/home/pawamoy/.cache/pdm/packages/pluggy-1.0.0-py2.py3-none-any/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_pause>]
          │         └ <function pytest_pyfunc_call at 0x7f388c5a8680>
          └ <HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/home/pawamoy/.cache/pdm/packages/pytest-6.2.5-py3-none...

  File "/home/pawamoy/.cache/pdm/packages/pytest-6.2.5-py3-none-any/lib/_pytest/python.py", line 183, in pytest_pyfunc_call
    result = testfunction(**testargs)
             │              └ {'server': <tests.conftest._Aria2Server object at 0x7f3885d72a00>}
             └ <bound method TestDownloadClass.test_pause of <tests.test_downloads.TestDownloadClass object at 0x7f3885d714c0>>

  File "/media/data/dev/aria2p/tests/test_downloads.py", line 290, in test_pause
    self.download.pause()
    │    │        └ <function Download.pause at 0x7f38873f0220>
    │    └ <aria2p.downloads.Download object at 0x7f3885d72540>
    └ <tests.test_downloads.TestDownloadClass object at 0x7f3885d714c0>

  File "/media/data/dev/aria2p/src/aria2p/downloads.py", line 1043, in pause
    result = self.api.pause([self], force=force)[0]
             │    │   │      │            └ False
             │    │   │      └ <aria2p.downloads.Download object at 0x7f3885d72540>
             │    │   └ <function API.pause at 0x7f38873f1620>
             │    └ API(Client(host='http://localhost', port=15501, secret='********'))
             └ <aria2p.downloads.Download object at 0x7f3885d72540>

> File "/media/data/dev/aria2p/src/aria2p/api.py", line 536, in pause
    pause_func(download.gid)
    │          │        └ <property object at 0x7f38873e8090>
    │          └ <aria2p.downloads.Download object at 0x7f3885d72540>
    └ <bound method Client.pause of Client(host='http://localhost', port=15501, secret='********')>

  File "/media/data/dev/aria2p/src/aria2p/client.py", line 670, in pause
    return self.call(self.PAUSE, [gid])  # type: ignore
           │    │    │    │       └ '0a6635c602761000'
           │    │    │    └ 'aria2.pause'
           │    │    └ Client(host='http://localhost', port=15501, secret='********')
           │    └ <function Client.call at 0x7f388755f600>
           └ Client(host='http://localhost', port=15501, secret='********')

  File "/media/data/dev/aria2p/src/aria2p/client.py", line 262, in call
    return self.res_or_raise(self.post(payload))
           │    │            │    │    └ '{"jsonrpc": "2.0", "method": "aria2.pause", "id": -1, "params": ["0a6635c602761000"]}'
           │    │            │    └ <function Client.post at 0x7f388755f7e0>
           │    │            └ Client(host='http://localhost', port=15501, secret='********')
           │    └ <staticmethod(<function Client.res_or_raise at 0x7f388755f920>)>
           └ Client(host='http://localhost', port=15501, secret='********')

  File "/media/data/dev/aria2p/src/aria2p/client.py", line 389, in res_or_raise
    raise Client.response_as_exception(response)
          │      │                     └ {'id': -1, 'jsonrpc': '2.0', 'error': {'code': 1, 'message': 'GID 0a6635c602761000 is not found'}}
          │      └ <staticmethod(<function Client.response_as_exception at 0x7f388755f880>)>
          └ <class 'aria2p.client.Client'>

aria2p.client.ClientException: GID 0a6635c602761000 is not found
